baseURL = 'https://burchbytes.com/'
languageCode = 'en-us'
title = 'Eli Burch'
theme = 'hello-friend-ng'

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    # Subtitle for home
    homeSubtitle = ""

    # Background image
    backgroundImage = "images/background.jpg"

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Enable sharing buttons, if you like
    enableSharingButtons = false

    # Show a global language switcher in the navigation bar
    enableGlobalLanguageMenu = false

    # Allow user to change their theme
    enableThemeToggle = true

    # Metadata mostly used in document's head
    description = "Eli Burch's Blog/Homepage"
    keywords = "homepage, blog"
    images = [""]

    [taxonomies]
        category = "blog"
        tag      = "tags"
        series   = "series"

    [[params.social]]
        name = "email"
        url  = "mailto:eli.burch@burchbytes.com"

    [[params.social]]
        name = "github"
        url  = "https://github.com/redawl"

    [[params.social]]
        name = "linkedin"
        url  = "https://www.linkedin.com/in/eli-burch/"

[languages]
    [languages.en]
        title = "Eli Burch"
        copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [languages.en.params]
        subtitle  = "Assortment of stuff"
        readOtherPosts = "Read other posts"
        keywords = ""

    [languages.en.params.logo]
        logoMark = "burchbytes.com ~ #"
        logoText = " "
        logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    # And you can even create generic menu
    [menu]
        [[menu.main]]
            identifier = "about"
            name       = "About"
            url        = "/about"
        [[menu.main]]
            identifier = "hardware-hacking"
            name       = "Hardware Hacking"
            url        = "/hardware-hacking"
        [[menu.main]]
            identifier = "projects"
            name       = "Projects"
            url        = "/projects"

